-------------------
-- CRIAÇÃO DO BD --
-------------------

--criando tabela administrador
CREATE TABLE ADMINISTRADOR (
EMAIL VARCHAR(40),
NOME VARCHAR(80),
PATRAO VARCHAR(40),
CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY (EMAIL),
CONSTRAINT FK_ADM_PATRAO FOREIGN KEY (PATRAO) REFERENCES ADMINISTRADOR (EMAIL)
);

--criando tabela loteamento
CREATE TABLE LOTEAMENTO (
COD VARCHAR(6),
NOME VARCHAR(40),
END_CEP VARCHAR(8),
END_LOGRADOURO VARCHAR(80),
CONSTRAINT PK_LOTEAMENTO PRIMARY KEY (COD)
);

--criando tabela acesso
CREATE TABLE ACESSO (
EMAIL VARCHAR(40),
COD VARCHAR(6),
CONSTRAINT PK_ACESSO PRIMARY KEY (EMAIL, COD),
CONSTRAINT FK_ACESSO_ADM FOREIGN KEY (EMAIL) REFERENCES ADMINISTRADOR (EMAIL),
CONSTRAINT FK_ACESSO_LOTEAMENTO FOREIGN KEY (COD) REFERENCES LOTEAMENTO (COD)
);

--criando tabela lote
CREATE TABLE LOTE (
COD VARCHAR(6),
NUMERO VARCHAR(4),
QUADRA VARCHAR(1),
VALOR VARCHAR(20),
CONSTRAINT PK_LOTE PRIMARY KEY (COD, NUMERO),
CONSTRAINT FK_LOTE_LOTEAMENTO FOREIGN KEY (COD) REFERENCES LOTEAMENTO (COD)
);

--criando tabela cliente
CREATE TABLE CLIENTE (
ID VARCHAR(4),
ENDERECO VARCHAR(80),
STATUS VARCHAR(7),
TELEFONE1 NUMBER(9),
TELEFONE2 NUMBER(9),
CPF VARCHAR(11) UNIQUE,
NOME VARCHAR(80),
CNPJ VARCHAR(14) UNIQUE,
RAZAO_SOCIAL VARCHAR(50),
CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);

--criando tabela compra
CREATE TABLE COMPRA (
COD VARCHAR(6),
NUMERO VARCHAR(4),
ID VARCHAR(4) NOT NULL,
DATA_COMPRA DATE,
CONSTRAINT PK_COMPRA PRIMARY KEY (COD, NUMERO),
CONSTRAINT FK_COMPRA_LOTE FOREIGN KEY (COD, NUMERO) REFERENCES LOTE (COD, NUMERO),
CONSTRAINT FK_COMPRA_CLIENTE FOREIGN KEY (ID) REFERENCES CLIENTE (ID)
);

-- criando tabela parcela
CREATE TABLE PARCELA (
COD VARCHAR(6),
NUMERO VARCHAR(4),
COD_PARCELA VARCHAR(9),
VALOR VARCHAR(10),
DATA DATE,
STATUS VARCHAR(7),
NUMERO_PARCELA NUMBER(3),
CONSTRAINT PK_PARCELA PRIMARY KEY (COD_PARCELA),
CONSTRAINT FK_PARCELA_COMPRA FOREIGN KEY (COD, NUMERO) REFERENCES COMPRA (COD, NUMERO)
);

--criando tabela empresa
CREATE TABLE EMPRESA (
CNPJ VARCHAR(14),
RAZAO_SOCIAL VARCHAR(50),
CONSTRAINT PK_EMPRESA PRIMARY KEY (CNPJ)
);

--criando tabela equipamento
CREATE TABLE EQUIPAMENTO (
COD VARCHAR(9),
NOME VARCHAR(20),
CONSTRAINT PK_EQUIPAMENTO PRIMARY KEY (COD)
);

--criando tabela possui
CREATE TABLE POSSUI (
CNPJ VARCHAR(14),
COD_EQUIP VARCHAR(9),
COD_LOTE VARCHAR(6),
NUMERO VARCHAR(4),
CONSTRAINT PK_POSSUI PRIMARY KEY (CNPJ, COD_EQUIP, COD_LOTE, NUMERO),
CONSTRAINT FK_POSSUI_EMPRESA FOREIGN KEY (CNPJ) REFERENCES EMPRESA (CNPJ),
CONSTRAINT FK_POSSUI_EQUIPAMENTO FOREIGN KEY (COD_EQUIP) REFERENCES EQUIPAMENTO (COD),
CONSTRAINT FK_POSSUI_LOTE FOREIGN KEY (COD_LOTE, NUMERO) REFERENCES LOTE (COD, NUMERO)
);